name: CI
on: 
  push:
    branches:
      - main
      - 'features/**'
  pull_request: 
  
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: build
        run: npm run build
